### Récupération de tout les restaurants 
GET   http://localhost:3000/restaurant


### Récupération d'un restaurant
GET   http://localhost:3000/restaurant/2

### Creer un restaurant 
POST   http://localhost:3000/restaurant
Content-Type: application/json

{
  "name": "fsd",
  "city": "sdqsfsd",
  "image": "sqdqfsdfsd"
}

### Creer un restaurant 
DELETE http://localhost:3000/restaurant/14
Content-Type: application/json

### Modifier un restaurant
patch   http://localhost:3000/restaurant/1
Content-Type: application/json

{
  "name": "La palette du gout",
  "city": "Le Canal Saint-Martin",
  "image": "images/La_palette_du_gout.jpg"
}
